In [57]:
import torch
import numpy as np

In [11]:
a = torch.arange(4*3*2*5).reshape(4,3,2,5)
print(a[0])

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])


In [12]:
a = a.reshape(2, 6, 2, 5)
print(a[0])

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]],

        [[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]],

        [[50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])


In [55]:
iters = 3
a = torch.tensor([
        [ [[0]], [[1]], [[2]], [[3]] ],
        [ [[4]], [[5]], [[6]], [[7]] ],
        [ [[8]], [[9]], [[10]], [[11]] ]
    ])
b = a.clone()
# b = torch.tensor([
#         [ [[0]], [[1]] ],
#         [ [[4]], [[5]] ],
#         [ [[8]], [[9]] ],
#         [ [[2]], [[3]] ],
#         [ [[6]], [[7]] ],
#         [ [[10]], [[11]] ]
#     ])

In [51]:
a.shape

torch.Size([3, 4, 1, 1])

In [52]:
torch.cat([ b[i:i+iters] for i in list(range(0, len(b), iters))], dim=1).shape

torch.Size([3, 4, 1, 1])

In [56]:
torch.all(a == torch.cat([ b[i:i+iters] for i in list(range(0, len(b), iters))], dim=1))

tensor(1, dtype=torch.uint8)

In [40]:
torch.cat([b[:2], b[2:]], dim=1)

tensor([[[[0]],

         [[1]],

         [[2]],

         [[3]]],


        [[[4]],

         [[5]],

         [[6]],

         [[7]]]])

In [34]:
torch.cat([b[:2], b[2:]], dim=1)

tensor([[[[0]],

         [[1]],

         [[2]],

         [[3]]],


        [[[4]],

         [[5]],

         [[6]],

         [[7]]]])

In [83]:
a = [np.arange(0, 6).reshape(2, 3), np.arange(6, 15).reshape(3, 3)]

In [85]:
np.concatenate(a)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [82]:
a

[array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])]

In [76]:
a[1]

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [77]:
a

[array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8,  9],
        [10, 11, 12, 13]])]

In [84]:
np.array(a)

array([array([[0, 1, 2],
       [3, 4, 5]]),
       array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])], dtype=object)