In [118]:
SUDOKU_PATH = "/Users/andrew/Desktop/sudoku"

import torch
import torch.nn.functional as F
import numpy as np
import keras.utils

from enum import Enum

import sys
sys.path.append(SUDOKU_PATH + '/src/sudoku')

from Dict import Dict
from solutions import Solutions
import utils

/Users/andrew/anaconda/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/Users/andrew/anaconda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [2]:
solutions = Solutions(SUDOKU_PATH + '/data/solutions9.txt')

Successfully loaded from /Users/andrew/Desktop/sudoku/data/solutions9.txt


In [24]:
nums = solutions.get_num_puzzles_per_hint()
for s in nums:
    print(s.stringify(), ["{}: {}".format(k, nums[s][k]) for k in sorted(nums[s])])

2.2.1234341223414123 ['4: 11', '5: 37', '6: 81', '7: 138', '8: 199', '9: 269', '10: 333', '11: 373', '12: 364', '13: 290', '14: 116', '15: 16', '16: 1']
2.2.1234341243212143 ['5: 11', '6: 38', '7: 92', '8: 159', '9: 249', '10: 339', '11: 399', '12: 421', '13: 339', '14: 116', '15: 16', '16: 1']
2.2.1234432131422413 ['4: 8', '5: 40', '6: 91', '7: 141', '8: 197', '9: 256', '10: 322', '11: 366', '12: 370', '13: 304', '14: 117', '15: 16', '16: 1']
2.2.1234342121434312 ['4: 5', '5: 35', '6: 87', '7: 146', '8: 219', '9: 307', '10: 373', '11: 414', '12: 415', '13: 312', '14: 117', '15: 16', '16: 1']
2.2.1234342143122143 ['4: 6', '5: 42', '6: 90', '7: 159', '8: 226', '9: 295', '10: 348', '11: 392', '12: 393', '13: 303', '14: 116', '15: 16', '16: 1']
2.2.1234341221434321 ['5: 3', '6: 32', '7: 91', '8: 169', '9: 252', '10: 338', '11: 407', '12: 425', '13: 317', '14: 115', '15: 16', '16: 1']
2.2.1234432124133142 ['4: 8', '5: 38', '6: 87', '7: 138', '8: 193', '9: 269', '10: 326', '11: 374', '12: 3

In [25]:
solutions = Solutions(SUDOKU_PATH + '/data/solutions10.txt')
nums = solutions.get_num_puzzles_per_hint()
for s in nums:
    print(s.stringify(), ["{}: {}".format(k, nums[s][k]) for k in sorted(nums[s])])

Successfully loaded from /Users/andrew/Desktop/sudoku/data/solutions10.txt
2.2.1234341223414123 ['4: 11', '5: 37', '6: 81', '7: 138', '8: 199', '9: 269', '10: 333', '11: 373', '12: 364', '13: 290', '14: 116', '15: 16', '16: 1']
2.2.1234341243212143 ['5: 11', '6: 38', '7: 93', '8: 161', '9: 252', '10: 343', '11: 402', '12: 424', '13: 340', '14: 116', '15: 16', '16: 1']
2.2.1234432131422413 ['4: 8', '5: 40', '6: 91', '7: 141', '8: 197', '9: 256', '10: 322', '11: 366', '12: 370', '13: 304', '14: 117', '15: 16', '16: 1']
2.2.1234342121434312 ['4: 5', '5: 35', '6: 87', '7: 146', '8: 219', '9: 307', '10: 373', '11: 414', '12: 415', '13: 312', '14: 117', '15: 16', '16: 1']
2.2.1234342143122143 ['4: 6', '5: 42', '6: 90', '7: 159', '8: 226', '9: 295', '10: 348', '11: 392', '12: 393', '13: 303', '14: 116', '15: 16', '16: 1']
2.2.1234341221434321 ['5: 3', '6: 32', '7: 91', '8: 169', '9: 252', '10: 338', '11: 407', '12: 425', '13: 317', '14: 115', '15: 16', '16: 1']
2.2.1234432124133142 ['4: 8', '

In [11]:
min(utils.flatten([v.keys() for v in nums.values()]))

4

In [15]:
counts = nums
min_hints = min(utils.flatten([v.keys() for v in counts.values()]))
min_hint_counts = {k: v[min_hints] for k, v in counts.items()}
min_board = min(min_hint_counts, key=lambda k: min_hint_counts[k])
return min_board

In [17]:
for k, v in min_hint_counts.items():
    print(k.stringify(), v)

2.2.1234341223414123 11
2.2.1234341243212143 0
2.2.1234432131422413 8
2.2.1234342121434312 5
2.2.1234342143122143 6
2.2.1234341221434321 0
2.2.1234432124133142 8
2.2.1234341241232341 7
2.2.1234432121433412 2
2.2.1234431234212143 5
2.2.1234431221433421 11
2.2.1234432134122143 1


In [20]:
min_hint_counts[min_board]

0

In [21]:
min_board.stringify()

'2.2.1234341243212143'

In [82]:
a

[array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])]

In [76]:
a[1]

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13]])

array([[[[0.2, 0.2, 0.2, 0.2, 0.2],
         [1. , 0. , 0. , 0. , 0. ],
         [0. , 1. , 0. , 0. , 0. ],
         [0. , 0. , 1. , 0. , 0. ]],

        [[0. , 0. , 0. , 1. , 0. ],
         [0. , 0. , 0. , 0. , 1. ],
         [0.2, 0.2, 0.2, 0.2, 0.2],
         [1. , 0. , 0. , 0. , 0. ]],

        [[0. , 1. , 0. , 0. , 0. ],
         [0. , 0. , 1. , 0. , 0. ],
         [0. , 0. , 0. , 1. , 0. ],
         [0. , 0. , 0. , 0. , 1. ]]],


       [[[0.2, 0.2, 0.2, 0.2, 0.2],
         [1. , 0. , 0. , 0. , 0. ],
         [0. , 1. , 0. , 0. , 0. ],
         [0. , 0. , 1. , 0. , 0. ]],

        [[0. , 0. , 0. , 1. , 0. ],
         [0. , 0. , 0. , 0. , 1. ],
         [0.2, 0.2, 0.2, 0.2, 0.2],
         [1. , 0. , 0. , 0. , 0. ]],

        [[0. , 1. , 0. , 0. , 0. ],
         [0. , 0. , 1. , 0. , 0. ],
         [0. , 0. , 0. , 1. , 0. ],
         [0. , 0. , 0. , 0. , 1. ]]]])

In [150]:
not a[:,:,:,1:][0][0][0].any()

True

SyntaxError: positional argument follows keyword argument (<ipython-input-142-82344dce924b>, line 1)

In [16]:
print(f"{a} is 234")

432 is 234


In [14]:
a = 432

In [19]:
a = torch.autograd.Variable(torch.Tensor(4))

In [21]:
a.requires_grad

False

In [24]:
torch.Tensor(4).requires_grad

False

In [27]:
torch.Tensor(4).requires_grad = True

In [28]:
torch.arange(4)

tensor([0, 1, 2, 3])

In [ ]:
encoding = torch.zeros(x.shape + (torch.max(x)+1, ))
dim = len(x.shape)
x = x.view(x.shape + (1, ))
return encoding.scatter_(dim, x, 1)

In [203]:
def one_hot_encode(x):
    encoding = torch.zeros(x.shape + (torch.max(x)+1, ))
    if x.is_cuda:
        encoding = encoding.cuda(x.get_device())
    dim = len(x.shape)
    x = x.view(x.shape + (1, ))
    return encoding.scatter_(dim, x, 1)

def puzzle_as_dist(x):
    tensor = type(x) == torch.Tensor
    if tensor:
        x = x.numpy()
    p = np.ones(np.max(x))/np.max(x)
    x = keras.utils.to_categorical(x, num_classes=np.max(x)+1, dtype='float64')
    x = x[:,:,:,1:]
    x = np.apply_along_axis(lambda a: a if a.any() else p, len(x.shape)-1, x)
    return torch.tensor(x) if tensor else x
    

In [244]:
def puzzle_as_dist(x):
    x = one_hot_encode(x)
    
    # to account for arbitrary dimensionality
    dims = len(x.shape)
    order = [dims-1] + list(range(dims-1))
    x = x.permute(order)[1:]
    order = list(range(1, dims)) + [0]
    x = x.permute(order)
    
    x = x.numpy()
    p = np.ones(x.shape[-1])/x.shape[-1]
    x = np.apply_along_axis(lambda a: a if a.any() else p, len(x.shape)-1, x)
    return torch.tensor(x)

In [256]:
a = torch.arange(2*3*4).view(2,3,4)
b = torch.arange(2*3*4).view(2,3,4)
torch.cat([a, b], dim=len(a.shape)-1)

tensor([[[ 0,  1,  2,  3,  0,  1,  2,  3],
         [ 4,  5,  6,  7,  4,  5,  6,  7],
         [ 8,  9, 10, 11,  8,  9, 10, 11]],

        [[12, 13, 14, 15, 12, 13, 14, 15],
         [16, 17, 18, 19, 16, 17, 18, 19],
         [20, 21, 22, 23, 20, 21, 22, 23]]])

In [231]:
a = torch.stack([torch.arange(2*3)]*4).view(2,3,4)
a = one_hot_encode(a)
dims = len(a.shape)
order = [dims-1] + list(range(dims-1))
a = a.permute(order)[1:]
order = list(range(1, dims)) + [0]
a = a.permute(order)
#.permute(range(len(a.shape)-1))

tensor([[[[0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0.],
          [0., 1., 0., 0., 0.],
          [0., 0., 1., 0., 0.]],

         [[0., 0., 0., 1., 0.],
          [0., 0., 0., 0., 1.],
          [0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0.]],

         [[0., 1., 0., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.],
          [0., 0., 0., 0., 1.]]],


        [[[0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0.],
          [0., 1., 0., 0., 0.],
          [0., 0., 1., 0., 0.]],

         [[0., 0., 0., 1., 0.],
          [0., 0., 0., 0., 1.],
          [0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0.]],

         [[0., 1., 0., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.],
          [0., 0., 0., 0., 1.]]]])

In [205]:
a = torch.stack([torch.arange(2*3)]*4).view(2,3,4)
puzzle_as_dist(a)

tensor([[[[0.2000, 0.2000, 0.2000, 0.2000, 0.2000],
          [1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 1.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 1.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000, 1.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 1.0000],
          [0.2000, 0.2000, 0.2000, 0.2000, 0.2000],
          [1.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

         [[0.0000, 1.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 1.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 1.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 1.0000]]],


        [[[0.2000, 0.2000, 0.2000, 0.2000, 0.2000],
          [1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 1.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 1.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000, 1.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 1.0000],
          [0.2000, 0.2000, 0.2000, 0.2000, 0.2000],
  

In [185]:
torch.tensor(puzzle_as_dist(a.numpy())).shape

torch.Size([2, 3, 4, 5])

In [187]:
type(torch.tensor(puzzle_as_dist(a.numpy()))) == torch.Tensor

True

In [95]:
a[0,:] * encoding[:,0]

tensor([0.2500, 0.0000, 0.0000, 0.0000])

In [93]:
encoding[:,0]

tensor([1., 0., 0., 0.])

In [257]:
from torch import FloatTensor
from torch.autograd import Variable


# Define the leaf nodes
a = Variable(FloatTensor([4]))

weights = [Variable(FloatTensor([i]), requires_grad=True) for i in (2, 5, 9, 7)]

# unpack the weights for nicer assignment
w1, w2, w3, w4 = weights

b = w1 * a
c = w2 * a
d = w3 * b + w4 * c
L = (10 - d)

L.backward()

for index, weight in enumerate(weights, start=1):
    gradient, *_ = weight.grad.data
    print(f"Gradient of w{index} w.r.t to L: {gradient}")

Gradient of w1 w.r.t to L: -36.0
Gradient of w2 w.r.t to L: -28.0
Gradient of w3 w.r.t to L: -8.0
Gradient of w4 w.r.t to L: -20.0


In [305]:
v = torch.arange(3, dtype=torch.double)
a = torch.arange(6, dtype=torch.double).view(3,2) + 1
a.requires_grad = True
t = torch.arange(2, dtype=torch.double) + 4
a

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], requires_grad=True)

In [306]:
L = torch.sum(t - v.matmul(a))
L.backward()
print(a.grad.data)

tensor([[-0., -0.],
        [-1., -1.],
        [-2., -2.]])


In [308]:
print(t)
print(v.matmul(a))
print(t - v.matmul(a))

tensor([4., 5.])
tensor([13., 16.], grad_fn=<SqueezeBackward3>)
tensor([ -9., -11.], grad_fn=<ThSubBackward>)


In [300]:
t - v.matmul(a)

tensor([ -9., -11.], grad_fn=<ThSubBackward>)

tensor([[-0., -0.],
        [-1., -1.],
        [-2., -2.]])

In [302]:
v.matmul(a)

tensor([13., 16.], grad_fn=<SqueezeBackward3>)

In [303]:
v

tensor([0., 1., 2.])

In [304]:
a

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], requires_grad=True)