In [2]:
from board import Board
from solutions import Solutions
import numpy as np

In [5]:
board = Board(2, 2)
board.write(2, 0, 1)
board.write(0, 2, 1)
board

array([[0, 0, 1, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [9]:
board.pencilMarks[0][0]

array([0, 1, 1, 1], dtype=int8)

In [10]:
board.pencilMarks[0][1]

array([0, 1, 1, 1], dtype=int8)

In [11]:
board.pencilMarks[1][0]

array([0, 1, 1, 1], dtype=int8)

In [12]:
board.pencilMarks[1][1]

array([1, 1, 1, 1], dtype=int8)

In [13]:
# Hidden singles:
"""
For each row, col, and box S:
    for each digit d:
        Get pencil marks for digit d in S
        If there is only 1 pencil mark with d in S, write it"""

'\nFor each row, col, and box S:\n    for each digit d:\n        Get pencil marks for digit d in S\n        If there is only 1 pencil mark with d in S, write it'